@echo off
title Aurora Services
mode 75,20
color b
echo Aurora - Slow But Not Too Slow
set /p IP=Enter Host: 
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
echo One Moment...
timeout /t 3

cls

echo off
:top
color c
PING -n 1 %IP% | FIND "TTL="
IF ERRORLEVEL 1 (SET in=c & echo Connection Timed Out.)
ping 127.0.0.1 -n 2 > nul

color b
IF ERRORLEVEL 1 (SET in=c & echo Connection Timed Out.)
ping 127.0.0.1 -n 2 > nul
GoTo top